Repository jinx-vi-0/BlogLog, pull requests merged in 2024-10, with the labels that each got.

#16 Refactor Post and User models
  package-lock.json
  package.json
  public/css/style.css
  public/img/user.png
  server/models/Post.js
  server/models/User.js
  server/routes/admin.js
  server/routes/main.js
  views/admin/manage-users.ejs
  views/admin/profile.ejs
  views/layouts/admin.ejs
  views/partials/header.ejs
  views/partials/header_admin.ejs
  views/post.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#49 Add contact page and data stored in database
  package-lock.json
  package.json
  public/css/style.css
  server/config/nodemailerConfig.js
  server/models/contactMessage.js
  server/routes/main.js
  views/contact.ejs
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#48 Beautified the Add-Post Page
  views/admin/add-post.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#51 Added application logs with morgan
  .gitignore
  app.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level1

#59 Added Toggle for Password Visibility and Implemented Functional Log Out Button
  server/routes/admin.js
  server/routes/main.js
  views/about.ejs
  views/admin/index.ejs
  views/layouts/admin.ejs
  views/layouts/main.ejs
  views/partials/header.ejs
  views/partials/header_admin.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#68 Fixed Authorization Issue at Signup
  server/routes/admin.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#79 added option in home page to create a blog
  public/css/style.css
  views/index.ejs
  views/partials/header.ejs
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#89 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr_checker.yaml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#90 fixed Footer
  package-lock.json
  public/css/style.css
  views/admin/dashboard.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#64 Added dark mode toggle, button design changes, and adjusted layout
  package-lock.json
  public/css/style.css
  public/js/script.js
  views/layouts/main.ejs
  views/partials/search.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#93 Added Validation At Register Page
  server/routes/admin.js
  views/admin/register.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#99 Small fixes
  example.env
  public/js/script.js
  views/contact.ejs
  views/layouts/main.ejs
  views/partials/header.ejs
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1

#112 Added Validations for Add-Post & Contact-Us
  server/routes/admin.js
  server/routes/main.js
  server/validations/authValidator.js
  views/admin/add-post.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#113 Improved "Create Post" Page
  views/admin/add-post.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2
